app:
  version: 0.0.1
  formatted-version: "v${app.version}"
  java.version: "@java.version@"

spring:
  application:
    name: "Lambda Spring Boot"
  output.ansi.enabled: detect
  profiles.active: dev

logging:
  level:
    org.springframework.web: ERROR
    com.kapresoft: DEBUG

motto:
  house: "Targaryen"
  message: "Fire and Blood"